[project]
name = "whale-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.5.2",
    "matplotlib>=3.10.9",
    "pandas>=3.0.2",
    "polars>=1.40.0",
    "pyarrow>=23.0.1",
    "scikit-learn>=1.8.0",
    "visidata>=3.3",
]
